/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pmn.gui;

/**
 *
 * @author enriq_000
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnBiseccion = new javax.swing.JButton();
        btnCalcular2 = new javax.swing.JButton();
        btnCalcular3 = new javax.swing.JButton();
        btnCalcular4 = new javax.swing.JButton();
        btnCalcular5 = new javax.swing.JButton();
        btnCalcular6 = new javax.swing.JButton();
        btnCalcular7 = new javax.swing.JButton();
        btnCalcular8 = new javax.swing.JButton();
        btnCalcular9 = new javax.swing.JButton();
        btnCalcular10 = new javax.swing.JButton();
        btnCalcular11 = new javax.swing.JButton();
        btnCalcular12 = new javax.swing.JButton();
        btnCalcular13 = new javax.swing.JButton();
        btnCalcular14 = new javax.swing.JButton();
        btnCalcular15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodos Númericos");

        panelPrincipal.setBackground(new java.awt.Color(0, 102, 153));
        panelPrincipal.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Métodos Numericos");

        btnCalcular.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Método de Newton");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnBiseccion.setBackground(new java.awt.Color(102, 102, 255));
        btnBiseccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBiseccion.setText("Método de Bisección");
        btnBiseccion.setBorder(null);
        btnBiseccion.setBorderPainted(false);
        btnBiseccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBiseccion.setOpaque(false);
        btnBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiseccionActionPerformed(evt);
            }
        });

        btnCalcular2.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular2.setText("Método de la Regla Falsa");
        btnCalcular2.setBorder(null);
        btnCalcular2.setBorderPainted(false);
        btnCalcular2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular2.setOpaque(false);
        btnCalcular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular2ActionPerformed(evt);
            }
        });

        btnCalcular3.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular3.setText("Método de la Secante");
        btnCalcular3.setBorder(null);
        btnCalcular3.setBorderPainted(false);
        btnCalcular3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular3.setOpaque(false);
        btnCalcular3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular3ActionPerformed(evt);
            }
        });

        btnCalcular4.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular4.setText("Método de Gauss Jordan");
        btnCalcular4.setBorder(null);
        btnCalcular4.setBorderPainted(false);
        btnCalcular4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular4.setOpaque(false);
        btnCalcular4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular4ActionPerformed(evt);
            }
        });

        btnCalcular5.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular5.setText("Método de Matriz Inversa");
        btnCalcular5.setBorder(null);
        btnCalcular5.setBorderPainted(false);
        btnCalcular5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular5.setOpaque(false);
        btnCalcular5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular5ActionPerformed(evt);
            }
        });

        btnCalcular6.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular6.setText("Método de Gauss Seidel");
        btnCalcular6.setBorder(null);
        btnCalcular6.setBorderPainted(false);
        btnCalcular6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular6.setOpaque(false);
        btnCalcular6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular6ActionPerformed(evt);
            }
        });

        btnCalcular7.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular7.setText("Método Regresión Lineal");
        btnCalcular7.setBorder(null);
        btnCalcular7.setBorderPainted(false);
        btnCalcular7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular7.setOpaque(false);
        btnCalcular7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular7ActionPerformed(evt);
            }
        });

        btnCalcular8.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular8.setText("Método Regresión Polinomial");
        btnCalcular8.setBorder(null);
        btnCalcular8.setBorderPainted(false);
        btnCalcular8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular8.setOpaque(false);
        btnCalcular8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular8ActionPerformed(evt);
            }
        });

        btnCalcular9.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular9.setText("Método Regresión Multiple");
        btnCalcular9.setBorder(null);
        btnCalcular9.setBorderPainted(false);
        btnCalcular9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular9.setOpaque(false);
        btnCalcular9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular9ActionPerformed(evt);
            }
        });

        btnCalcular10.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular10.setText("Método Interpolación Newton");
        btnCalcular10.setBorder(null);
        btnCalcular10.setBorderPainted(false);
        btnCalcular10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular10.setOpaque(false);
        btnCalcular10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular10ActionPerformed(evt);
            }
        });

        btnCalcular11.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular11.setText("Método Interpolación Lagrange");
        btnCalcular11.setBorder(null);
        btnCalcular11.setBorderPainted(false);
        btnCalcular11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular11.setOpaque(false);
        btnCalcular11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular11ActionPerformed(evt);
            }
        });

        btnCalcular12.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular12.setText("Regla del Rectangulo");
        btnCalcular12.setBorder(null);
        btnCalcular12.setBorderPainted(false);
        btnCalcular12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular12.setOpaque(false);
        btnCalcular12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular12ActionPerformed(evt);
            }
        });

        btnCalcular13.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular13.setText("Regla del Trapecio");
        btnCalcular13.setBorder(null);
        btnCalcular13.setBorderPainted(false);
        btnCalcular13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular13.setOpaque(false);
        btnCalcular13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular13ActionPerformed(evt);
            }
        });

        btnCalcular14.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular14.setText("Regla de 1/3 Simpson");
        btnCalcular14.setBorder(null);
        btnCalcular14.setBorderPainted(false);
        btnCalcular14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular14.setOpaque(false);
        btnCalcular14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular14ActionPerformed(evt);
            }
        });

        btnCalcular15.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular15.setText("Regla de 3/8 Simpson");
        btnCalcular15.setBorder(null);
        btnCalcular15.setBorderPainted(false);
        btnCalcular15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular15.setOpaque(false);
        btnCalcular15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCalcular9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcular10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcular11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addComponent(btnCalcular6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnCalcular7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnCalcular8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnCalcular3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcular4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcular5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnBiseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcular2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalcular15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnCalcular12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcular13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcular14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBiseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiseccionActionPerformed

        MetodoBiseccion mb = new MetodoBiseccion();
        mb.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnBiseccionActionPerformed

    private void btnCalcular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular2ActionPerformed

    private void btnCalcular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular3ActionPerformed

    private void btnCalcular4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular4ActionPerformed

    private void btnCalcular5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular5ActionPerformed

    private void btnCalcular6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular6ActionPerformed

    private void btnCalcular7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular7ActionPerformed

    private void btnCalcular8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular8ActionPerformed

    private void btnCalcular9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular9ActionPerformed

    private void btnCalcular10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular10ActionPerformed

    private void btnCalcular11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular11ActionPerformed

    private void btnCalcular12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular12ActionPerformed

    private void btnCalcular13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular13ActionPerformed

    private void btnCalcular14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular14ActionPerformed

    private void btnCalcular15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiseccion;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular10;
    private javax.swing.JButton btnCalcular11;
    private javax.swing.JButton btnCalcular12;
    private javax.swing.JButton btnCalcular13;
    private javax.swing.JButton btnCalcular14;
    private javax.swing.JButton btnCalcular15;
    private javax.swing.JButton btnCalcular2;
    private javax.swing.JButton btnCalcular3;
    private javax.swing.JButton btnCalcular4;
    private javax.swing.JButton btnCalcular5;
    private javax.swing.JButton btnCalcular6;
    private javax.swing.JButton btnCalcular7;
    private javax.swing.JButton btnCalcular8;
    private javax.swing.JButton btnCalcular9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
