/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pmn.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author enriq_000
 */
public class MetodoGaussSeidel extends javax.swing.JFrame {

    /**
     * Creates new form MetodoGaussSeidel
     */
    
    JTextField[][]campos = new JTextField[5][6];
    JLabel[]variables = new JLabel[6];
    
    int n;
    int m;
    private double tolerancia = 1; 
    
    public MetodoGaussSeidel() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        campos[0][0] = x00;
        campos[0][1] = x01;
        campos[0][2] = x02;
        campos[0][3] = x03;
        campos[0][4] = x04;
        campos[0][5] = x05;
        
        campos[1][0] = x10;
        campos[1][1] = x11;
        campos[1][2] = x12;
        campos[1][3] = x13;
        campos[1][4] = x14;
        campos[1][5] = x15;
        
        campos[2][0] = x20;
        campos[2][1] = x21;
        campos[2][2] = x22;
        campos[2][3] = x23;
        campos[2][4] = x24;
        campos[2][5] = x25;
        
        campos[3][0] = x30;
        campos[3][1] = x31;
        campos[3][2] = x32;
        campos[3][3] = x33;
        campos[3][4] = x34;
        campos[3][5] = x35;
        
        campos[4][0] = x40;
        campos[4][1] = x41;
        campos[4][2] = x42;
        campos[4][3] = x43;
        campos[4][4] = x44;
        campos[4][5] = x45;

        variables[0] = x0;
        variables[1] = x1;
        variables[2] = x2;
        variables[3] = x3;
        variables[4] = x4;
        variables[5] = x5;
        
        n=2;
        m=2;
        
        generarCampos();
        generarVariables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGaussSeidel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboLongitud = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        x00 = new javax.swing.JTextField();
        x10 = new javax.swing.JTextField();
        x20 = new javax.swing.JTextField();
        x30 = new javax.swing.JTextField();
        x40 = new javax.swing.JTextField();
        x01 = new javax.swing.JTextField();
        x02 = new javax.swing.JTextField();
        x03 = new javax.swing.JTextField();
        x04 = new javax.swing.JTextField();
        x05 = new javax.swing.JTextField();
        x11 = new javax.swing.JTextField();
        x21 = new javax.swing.JTextField();
        x31 = new javax.swing.JTextField();
        x41 = new javax.swing.JTextField();
        x22 = new javax.swing.JTextField();
        x32 = new javax.swing.JTextField();
        x12 = new javax.swing.JTextField();
        x42 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        x23 = new javax.swing.JTextField();
        x33 = new javax.swing.JTextField();
        x43 = new javax.swing.JTextField();
        x14 = new javax.swing.JTextField();
        x24 = new javax.swing.JTextField();
        x34 = new javax.swing.JTextField();
        x44 = new javax.swing.JTextField();
        x15 = new javax.swing.JTextField();
        x25 = new javax.swing.JTextField();
        x35 = new javax.swing.JTextField();
        x45 = new javax.swing.JTextField();
        x0 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTolerancia = new javax.swing.JTextField();
        btnEstablecerTolerancia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo Gauss Seidel");

        panelGaussSeidel.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de variables");

        comboLongitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        comboLongitud.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboLongitudPropertyChange(evt);
            }
        });

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gauss Seidel");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x00.setEnabled(false);

        x10.setEnabled(false);

        x20.setEnabled(false);

        x30.setEnabled(false);

        x40.setEnabled(false);

        x01.setEnabled(false);

        x02.setEnabled(false);

        x03.setEnabled(false);

        x04.setEnabled(false);

        x05.setEnabled(false);

        x11.setEnabled(false);

        x21.setEnabled(false);

        x31.setEnabled(false);
        x31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x31ActionPerformed(evt);
            }
        });

        x41.setEnabled(false);

        x22.setEnabled(false);

        x32.setEnabled(false);

        x12.setEnabled(false);

        x42.setEnabled(false);

        x13.setEnabled(false);

        x23.setEnabled(false);

        x33.setEnabled(false);

        x43.setEnabled(false);

        x14.setEnabled(false);

        x24.setEnabled(false);

        x34.setEnabled(false);

        x44.setEnabled(false);

        x15.setEnabled(false);

        x25.setEnabled(false);

        x35.setEnabled(false);

        x45.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(x40, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(x30)
                    .addComponent(x20)
                    .addComponent(x10)
                    .addComponent(x00))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x01, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x11)
                    .addComponent(x21)
                    .addComponent(x31)
                    .addComponent(x41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x02, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x22)
                    .addComponent(x32)
                    .addComponent(x12)
                    .addComponent(x42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x03, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x13)
                    .addComponent(x23)
                    .addComponent(x33)
                    .addComponent(x43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x05, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x35, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(x24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        x0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Porcentaje de Tolerancia");

        txtTolerancia.setText("1");
        txtTolerancia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtToleranciaFocusGained(evt);
            }
        });

        btnEstablecerTolerancia.setText("Establecer");
        btnEstablecerTolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstablecerToleranciaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nota: No ordena La matriz ");

        javax.swing.GroupLayout panelGaussSeidelLayout = new javax.swing.GroupLayout(panelGaussSeidel);
        panelGaussSeidel.setLayout(panelGaussSeidelLayout);
        panelGaussSeidelLayout.setHorizontalGroup(
            panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTolerancia)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstablecerTolerancia))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGaussSeidelLayout.createSequentialGroup()
                        .addComponent(btnResolver)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGaussSeidelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(x0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(299, 588, Short.MAX_VALUE))
            .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAplicar))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGaussSeidelLayout.setVerticalGroup(
            panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnAplicar)
                    .addComponent(comboLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGaussSeidelLayout.createSequentialGroup()
                        .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(x2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResolver)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGaussSeidelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstablecerTolerancia)
                            .addComponent(jLabel4)
                            .addComponent(txtTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGaussSeidel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGaussSeidel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarVariables(){
    
        switch (n){
        
            case 2:
                variables[0].setText("X");
                variables[1].setText("Y");
                variables[2].setText("R");
                variables[3].setText(null);
                variables[4].setText(null);
                variables[5].setText(null);
                
                break;
                
            case 3:
                variables[0].setText("X");
                variables[1].setText("Y");
                variables[2].setText("Z");
                variables[3].setText("R");
                variables[4].setText(null);
                variables[5].setText(null);
                break;
                
            case 4:
                variables[0].setText("W");
                variables[1].setText("X");
                variables[2].setText("Y");
                variables[3].setText("Z");
                variables[4].setText("R");
                variables[5].setText(null);
                break;
            case 5:
                variables[0].setText("V");
                variables[1].setText("W");
                variables[2].setText("X");
                variables[3].setText("Y");
                variables[4].setText("Z");
                variables[5].setText("R");

            default:
                break;
        }
    }
    private void generarCampos(){
    
        for (int i = 0; i < 5; i++) {
            
            for (int j = 0; j < 6; j++) {
                
                campos[i][j].setEnabled(false);
                
            }
        }
        
        for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < n+1; j++) {
                
                campos[i][j].setEnabled(true);
            }
        }
    }
    private void comboLongitudPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboLongitudPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_comboLongitudPropertyChange

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed

        n = Integer.parseInt(String.valueOf(comboLongitud.getSelectedItem()));

        limpiarCampos();
        generarCampos();
        generarVariables();
    }//GEN-LAST:event_btnAplicarActionPerformed
       
    private void limpiarCampos(){
    
        for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < n+1; j++) {
                
                campos[i][j].setText(null);
            }
        }
    }
    
    private void generarMatriz(){
        
        sistema = new double[n][n+1];
        
        try {
            for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < n+1; j++) {
                
                sistema[i][j] = Double.parseDouble(campos[i][j].getText());
            }
        }
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Asegurate de ingresar "
                    + "solamente valores númericos");
            limpiarCampos();
        }
        
    }
    double [][]sistema = new double[n][n+1];
    private void x31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x31ActionPerformed

    }//GEN-LAST:event_x31ActionPerformed

    boolean iniciado = false; 
    double[]valor = {0,0,0,0,0};
    
    double[]i1={0,0,0,0,0};
    double[]i2={0,0,0,0,0};
    
    double tolerancia1 = 100;
    double tolerancia2 = 100;
    double tolerancia3 = 100;
    double tolerancia4 = 100;
    double tolerancia5 = 100;
    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        generarMatriz();

        //Obtiene los coeficientes de la diagonal
        double[]coeficiente = new double[n];

        for (int i = 0; i <n; i++) {

            coeficiente[i] = sistema[i][i];

        }

        switch(n){

            case 2:
            do{
                valor[0] = sistema[0][2]+(-sistema[0][1]*valor[1]);
                valor[0] = valor[0]/coeficiente[0];

                valor[1] = sistema[1][2]+(-sistema[1][0]*valor[0]);
                valor[1] = valor[1]/coeficiente[1];

                System.out.println("x = "+valor[0]);
                System.out.println("y = "+valor[1]);
                System.out.println("_________________________________________");

                //Creación de los x1 y x2 para aplicar la formula
                i1[0] = i2[0];
                i1[1] = i2[1];

                i2[0]=valor[0];
                i2[1]=valor[1];

                //Aplicación de la formula para obtener el porcentaje de error
                tolerancia1 = Math.abs(((i2[0]-i1[0])/(i2[0]))*100);
                tolerancia2 = Math.abs(((i2[1]-i1[1])/(i2[1]))*100);

            }while(tolerancia1>this.tolerancia&&tolerancia2>this.tolerancia);

            break;

            case 3:
            do{
                valor[0] = sistema[0][3]+(-sistema[0][1]*valor[1])+(-sistema[0][2]*valor[2]);
                valor[0] = valor[0]/coeficiente[0];

                valor[1] = sistema[1][3]+(-sistema[1][0]*valor[0])+(-sistema[1][2]*valor[2]);
                valor[1] = valor[1]/coeficiente[1];

                valor[2] = sistema[2][3]+(-sistema[2][0]*valor[0])+(-sistema[2][1]*valor[1]);
                valor[2] = valor[2]/coeficiente[2];

                System.out.println("x = "+valor[0]);
                System.out.println("y = "+valor[1]);
                System.out.println("z = "+valor[2]);
                System.out.println("_________________________________________");

                i1[0] = i2[0];
                i1[1] = i2[1];
                i1[2] = i2[2];

                i2[0] = valor[0];
                i2[1] = valor[1];
                i2[2] = valor[2];

                tolerancia1 = Math.abs(((i2[0]-i1[0])/(i2[0]))*100);
                tolerancia2 = Math.abs(((i2[1]-i1[1])/(i2[1]))*100);
                tolerancia3 = Math.abs(((i2[2]-i1[2])/(i2[2]))*100);

            }while(tolerancia1>this.tolerancia&&tolerancia2>this.tolerancia&&tolerancia3>this.tolerancia);

            break;

            case 4:

            do{
                valor[0] = sistema[0][4]+(-sistema[0][1]*valor[1])+(-sistema[0][2]*valor[2])+(-sistema[0][3]*valor[3]);
                valor[0] = valor[0]/coeficiente[0];

                valor[1] = sistema[1][4]+(-sistema[1][0]*valor[0])+(-sistema[1][2]*valor[2])+(-sistema[1][3]*valor[3]);
                valor[1] = valor[1]/coeficiente[1];

                valor[2] = sistema[2][4]+(-sistema[2][0]*valor[0])+(-sistema[2][1]*valor[1])+(-sistema[2][3]*valor[3]);
                valor[2] = valor[2]/coeficiente[2];

                valor[3] = sistema[3][4]+(-sistema[3][0]*valor[0])+(-sistema[3][1]*valor[1])+(-sistema[3][2]*valor[2]);
                valor[3] = valor[3]/coeficiente[3];

                System.out.println("w = "+valor[0]);
                System.out.println("x = "+valor[1]);
                System.out.println("y = "+valor[2]);
                System.out.println("z = "+valor[3]);
                System.out.println("_________________________________________");

                i1[0] = i2[0];
                i1[1] = i2[1];
                i1[2] = i2[2];
                i1[3] = i2[3];

                i2[0] = valor[0];
                i2[1] = valor[1];
                i2[2] = valor[2];
                i2[3] = valor[3];

                tolerancia1 = Math.abs(((i2[0]-i1[0])/(i2[0]))*100);
                tolerancia2 = Math.abs(((i2[1]-i1[1])/(i2[1]))*100);
                tolerancia3 = Math.abs(((i2[2]-i1[2])/(i2[2]))*100);
                tolerancia4 = Math.abs(((i2[3]-i1[3])/(i2[3]))*100);

            }while(tolerancia1>this.tolerancia&&tolerancia2>this.tolerancia
                &&tolerancia3>this.tolerancia&&tolerancia4>this.tolerancia);

            break;

            case 5:

            do{
                valor[0] = sistema[0][5]+(-sistema[0][1]*valor[1])+(-sistema[0][2]*valor[2])+(-sistema[0][3]*valor[3])+(-sistema[0][4]*valor[4]);
                valor[0] = valor[0]/coeficiente[0];

                valor[1] = sistema[1][5]+(-sistema[1][0]*valor[0])+(-sistema[1][2]*valor[2])+(-sistema[1][3]*valor[3])+(-sistema[1][4]*valor[4]);
                valor[1] = valor[1]/coeficiente[1];

                valor[2] = sistema[2][5]+(-sistema[2][0]*valor[0])+(-sistema[2][1]*valor[1])+(-sistema[2][3]*valor[3])+(-sistema[2][4]*valor[4]);
                valor[2] = valor[2]/coeficiente[2];

                valor[3] = sistema[3][5]+(-sistema[3][0]*valor[0])+(-sistema[3][1]*valor[1])+(-sistema[3][2]*valor[2])+(-sistema[3][4]*valor[4]);
                valor[3] = valor[3]/coeficiente[3];

                valor[4] = sistema[4][5]+(-sistema[4][0]*valor[0])+(-sistema[4][1]*valor[1])+(-sistema[4][2]*valor[2])+(-sistema[4][3]*valor[3]);
                valor[4] = valor[4]/coeficiente[4];

                System.out.println("v = "+valor[0]);
                System.out.println("w = "+valor[1]);
                System.out.println("x = "+valor[2]);
                System.out.println("y = "+valor[3]);
                System.out.println("z = "+valor[4]);
                System.out.println("_________________________________________");

                i1[0] = i2[0];
                i1[1] = i2[1];
                i1[2] = i2[2];
                i1[3] = i2[3];
                i1[4] = i2[4];

                i2[0] = valor[0];
                i2[1] = valor[1];
                i2[2] = valor[2];
                i2[3] = valor[3];
                i2[4] = valor[4];

                tolerancia1 = Math.abs(((i2[0]-i1[0])/(i2[0]))*100);
                tolerancia2 = Math.abs(((i2[1]-i1[1])/(i2[1]))*100);
                tolerancia3 = Math.abs(((i2[2]-i1[2])/(i2[2]))*100);
                tolerancia4 = Math.abs(((i2[3]-i1[3])/(i2[3]))*100);
                tolerancia5 = Math.abs(((i2[4]-i1[4])/(i2[4]))*100);
            }while(tolerancia1>this.tolerancia&&tolerancia2>this.tolerancia
                &&tolerancia3>this.tolerancia&&tolerancia4>this.tolerancia&&tolerancia5>this.tolerancia);

            break;
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    private void txtToleranciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToleranciaFocusGained

        txtTolerancia.setText(null);
    }//GEN-LAST:event_txtToleranciaFocusGained

    private void btnEstablecerToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstablecerToleranciaActionPerformed

        try {

            this.setTolerancia(Double.parseDouble(txtTolerancia.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Asegurese de utilizar"
                + "solamente valores numericos para la tolerancia");
            txtTolerancia.setText(null);
            txtTolerancia.requestFocus();
        }

    }//GEN-LAST:event_btnEstablecerToleranciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoGaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoGaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoGaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoGaussSeidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoGaussSeidel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnEstablecerTolerancia;
    private javax.swing.JButton btnResolver;
    private javax.swing.JComboBox<String> comboLongitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelGaussSeidel;
    private javax.swing.JTextField txtTolerancia;
    private javax.swing.JLabel x0;
    private javax.swing.JTextField x00;
    private javax.swing.JTextField x01;
    private javax.swing.JTextField x02;
    private javax.swing.JTextField x03;
    private javax.swing.JTextField x04;
    private javax.swing.JTextField x05;
    private javax.swing.JLabel x1;
    private javax.swing.JTextField x10;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField x15;
    private javax.swing.JLabel x2;
    private javax.swing.JTextField x20;
    private javax.swing.JTextField x21;
    private javax.swing.JTextField x22;
    private javax.swing.JTextField x23;
    private javax.swing.JTextField x24;
    private javax.swing.JTextField x25;
    private javax.swing.JLabel x3;
    private javax.swing.JTextField x30;
    private javax.swing.JTextField x31;
    private javax.swing.JTextField x32;
    private javax.swing.JTextField x33;
    private javax.swing.JTextField x34;
    private javax.swing.JTextField x35;
    private javax.swing.JLabel x4;
    private javax.swing.JTextField x40;
    private javax.swing.JTextField x41;
    private javax.swing.JTextField x42;
    private javax.swing.JTextField x43;
    private javax.swing.JTextField x44;
    private javax.swing.JTextField x45;
    private javax.swing.JLabel x5;
    // End of variables declaration//GEN-END:variables


    public double getTolerancia() {
        return tolerancia;
    }

    public void setTolerancia(double tolerancia) {
        this.tolerancia = tolerancia;
    }
}