/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pmn.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enriq_000
 */
public class MetodoGaussJordan extends javax.swing.JFrame {

    /**
     * Creates new form MetodoGaussJordan
     */
    
    /**
     * Declaración de la variable global n, que indica el número de variables
     * del sistema de ecuaciones
     */
    int n;
    
    //Declaración de la matriz de JTextField
    JTextField[][]campos = new JTextField[5][6];
    
    //Declaración del arreglo de JLabel
    JLabel[]variables = new JLabel[6];
    
    public MetodoGaussJordan() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
 
        //Asignación de los campos de texto en la matriz de JTextField
        campos[0][0] = x00;
        campos[0][1] = x01;
        campos[0][2] = x02;
        campos[0][3] = x03;
        campos[0][4] = x04;
        campos[0][5] = x05;
        
        campos[1][0] = x10;
        campos[1][1] = x11;
        campos[1][2] = x12;
        campos[1][3] = x13;
        campos[1][4] = x14;
        campos[1][5] = x15;
        
        campos[2][0] = x20;
        campos[2][1] = x21;
        campos[2][2] = x22;
        campos[2][3] = x23;
        campos[2][4] = x24;
        campos[2][5] = x25;
        
        campos[3][0] = x30;
        campos[3][1] = x31;
        campos[3][2] = x32;
        campos[3][3] = x33;
        campos[3][4] = x34;
        campos[3][5] = x35;
        
        campos[4][0] = x40;
        campos[4][1] = x41;
        campos[4][2] = x42;
        campos[4][3] = x43;
        campos[4][4] = x44;
        campos[4][5] = x45;

        variables[0] = x0;
        variables[1] = x1;
        variables[2] = x2;
        variables[3] = x3;
        variables[4] = x4;
        variables[5] = x5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboLongitud = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        x00 = new javax.swing.JTextField();
        x10 = new javax.swing.JTextField();
        x20 = new javax.swing.JTextField();
        x30 = new javax.swing.JTextField();
        x40 = new javax.swing.JTextField();
        x01 = new javax.swing.JTextField();
        x02 = new javax.swing.JTextField();
        x03 = new javax.swing.JTextField();
        x04 = new javax.swing.JTextField();
        x05 = new javax.swing.JTextField();
        x11 = new javax.swing.JTextField();
        x21 = new javax.swing.JTextField();
        x31 = new javax.swing.JTextField();
        x41 = new javax.swing.JTextField();
        x22 = new javax.swing.JTextField();
        x32 = new javax.swing.JTextField();
        x12 = new javax.swing.JTextField();
        x42 = new javax.swing.JTextField();
        x13 = new javax.swing.JTextField();
        x23 = new javax.swing.JTextField();
        x33 = new javax.swing.JTextField();
        x43 = new javax.swing.JTextField();
        x14 = new javax.swing.JTextField();
        x24 = new javax.swing.JTextField();
        x34 = new javax.swing.JTextField();
        x44 = new javax.swing.JTextField();
        x15 = new javax.swing.JTextField();
        x25 = new javax.swing.JTextField();
        x35 = new javax.swing.JTextField();
        x45 = new javax.swing.JTextField();
        x0 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo Gauss Jordan");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Metodo Gauss Jordan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de variables");

        comboLongitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3" }));

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x00.setEnabled(false);

        x10.setEnabled(false);

        x20.setEnabled(false);

        x30.setEnabled(false);

        x40.setEnabled(false);

        x01.setEnabled(false);

        x02.setEnabled(false);

        x03.setEnabled(false);

        x04.setEnabled(false);

        x05.setEnabled(false);

        x11.setEnabled(false);

        x21.setEnabled(false);

        x31.setEnabled(false);
        x31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x31ActionPerformed(evt);
            }
        });

        x41.setEnabled(false);

        x22.setEnabled(false);

        x32.setEnabled(false);

        x12.setEnabled(false);

        x42.setEnabled(false);

        x13.setEnabled(false);

        x23.setEnabled(false);

        x33.setEnabled(false);

        x43.setEnabled(false);

        x14.setEnabled(false);

        x24.setEnabled(false);

        x34.setEnabled(false);

        x44.setEnabled(false);

        x15.setEnabled(false);

        x25.setEnabled(false);

        x35.setEnabled(false);

        x45.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(x40, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(x30)
                    .addComponent(x20)
                    .addComponent(x10)
                    .addComponent(x00))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x01, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x11)
                    .addComponent(x21)
                    .addComponent(x31)
                    .addComponent(x41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x02, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x22)
                    .addComponent(x32)
                    .addComponent(x12)
                    .addComponent(x42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x03, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(x13)
                    .addComponent(x23)
                    .addComponent(x33)
                    .addComponent(x43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(x04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x05, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(x34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x35, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(x44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(x24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        x0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        x5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnMenu.setBackground(new java.awt.Color(102, 102, 255));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMenu.setText("Menú Principal");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setOpaque(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(x0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnAplicar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnAplicar)
                    .addComponent(comboLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(387, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo encargado de enerar los campos necesarios para ingresar los 
     * valores de las variables en el sistema de ecuaciones
     */
    private void generarCampos(){
    
        for (int i = 0; i < 5; i++) {
            
            for (int j = 0; j < 6; j++) {
                
                campos[i][j].setEnabled(false);
            }
        }
        
        for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < n+1; j++) {
                
                campos[i][j].setEnabled(true);
            }
        }
    }
    
    /**
     * Evento encargado de invocar el metodo para generar los campos necesarios
     * para ingresar los valores de las variables en el sistema de ecuaciones
     * @param evt 
     */
    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed

        n = Integer.parseInt(String.valueOf(comboLongitud.getSelectedItem()));

        generarCampos();

        generarVariables();

    }//GEN-LAST:event_btnAplicarActionPerformed

    /**
     * Metodo encargado de generar las variables que se mostrarán según la 
     * cantidad de variables con las que cuenta el sistema de ecuaciones
     */
    private void generarVariables(){
    
        switch (n){
        
            case 2:
                variables[0].setText("X");
                variables[1].setText("Y");
                variables[2].setText("R");
                variables[3].setText(null);
                variables[4].setText(null);
                variables[5].setText(null);
                
                break;
                
            case 3:
                variables[0].setText("X");
                variables[1].setText("Y");
                variables[2].setText("Z");
                variables[3].setText("R");
                variables[4].setText(null);
                variables[5].setText(null);
                break;
                
            case 4:
                variables[0].setText("W");
                variables[1].setText("X");
                variables[2].setText("Y");
                variables[3].setText("Z");
                variables[4].setText("R");
                variables[5].setText(null);
                break;
            case 5:
                variables[0].setText("V");
                variables[1].setText("W");
                variables[2].setText("X");
                variables[3].setText("Y");
                variables[4].setText("Z");
                variables[5].setText("R");

            default:
                break;
        }
    }
    
    private void x31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x31ActionPerformed

    }//GEN-LAST:event_x31ActionPerformed

    double [][]sistema = new double[n][n+1];
    
    /**
     * Metodo encargado de generar la matriz de con los valores obtenidos de los
     * campos de texto
     */
    private void generarMatriz(){
        
        sistema = new double[n][n+1];
        
        for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < n+1; j++) {
                
                sistema[i][j] = Double.parseDouble(campos[i][j].getText());
            }
        }
    }
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnMenuActionPerformed

    String area = "";
    /**
     * Evento encargado de generar Paso a Paso el sistema de ecuaciones por el 
     * metodo de Gauss Jordan
     * @param evt del botón Calcular
     */
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        try{
        area="";
        generarMatriz();
        
        double divisor;
  
        int contador=0;
        
        do{
            
            divisor=sistema[contador][contador];
            
        //Divide la fila a analizar entre su diagonal para igualar el primer
        //valor a 1
        for (int i = 0; i < n+1; i++) {
            
            sistema[contador][i] =  sistema[contador][i]/divisor;
        }
        
        //Convertir a 0 las las columnas
        
            for (int i = 0; i < n; i++) {
                
                double producto = sistema[contador][contador]*sistema[i][contador];
                        
                for (int j = 0; j < n+1; j++) {
                    
                    if (i!=contador) {
                        
                        sistema[i][j] -= sistema[contador][j]*producto;
                    }
                }
            }

              //Mostrar matrices paso por paso en TextArea  
            for (int x=0; x < sistema.length; x++) {
                
                area+= "|";
                txtArea.setText(area);
                
            for (int y=0; y < sistema[x].length; y++) {
                
                area+=String.format("%.2f", sistema[x][y]);
                txtArea.setText(area);
                
            if (y!=sistema[x].length-1) 
                
                area+="\t";
                txtArea.setText(area);
            }
            area+="|"+"\n";
            txtArea.setText(area);
            }

        contador++;
        area+="________________________________"+"\n";
        txtArea.setText(area);
        
        }while(contador<n);

        area+="________________________________"+"\n";
        txtArea.setText(area);
        
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Asegurese de ingresar valores "
                    + "en todos los campos con el formato correcto");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> comboLongitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JLabel x0;
    private javax.swing.JTextField x00;
    private javax.swing.JTextField x01;
    private javax.swing.JTextField x02;
    private javax.swing.JTextField x03;
    private javax.swing.JTextField x04;
    private javax.swing.JTextField x05;
    private javax.swing.JLabel x1;
    private javax.swing.JTextField x10;
    private javax.swing.JTextField x11;
    private javax.swing.JTextField x12;
    private javax.swing.JTextField x13;
    private javax.swing.JTextField x14;
    private javax.swing.JTextField x15;
    private javax.swing.JLabel x2;
    private javax.swing.JTextField x20;
    private javax.swing.JTextField x21;
    private javax.swing.JTextField x22;
    private javax.swing.JTextField x23;
    private javax.swing.JTextField x24;
    private javax.swing.JTextField x25;
    private javax.swing.JLabel x3;
    private javax.swing.JTextField x30;
    private javax.swing.JTextField x31;
    private javax.swing.JTextField x32;
    private javax.swing.JTextField x33;
    private javax.swing.JTextField x34;
    private javax.swing.JTextField x35;
    private javax.swing.JLabel x4;
    private javax.swing.JTextField x40;
    private javax.swing.JTextField x41;
    private javax.swing.JTextField x42;
    private javax.swing.JTextField x43;
    private javax.swing.JTextField x44;
    private javax.swing.JTextField x45;
    private javax.swing.JLabel x5;
    // End of variables declaration//GEN-END:variables
}
