/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pmn.gui;

import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author enriq_000
 */
public class MetodoRegresionMultiple extends javax.swing.JFrame {

    /**
     * Creates new form MetodoRegresionMultiple
     */
    
    //Declaración de una matriz de tipo
    JTextField[][]campo = new JTextField[10][3];

    /**Declaración de la variable global n, que identifica la cantidad de 
     * puntos ingresados en la gráfica
    */
    int n;

    /**Declaración del arreglo que guardará todos los valores de X ingresados
     * en los campos de texto
    */
    /**Declaración del arreglo que guardará todos los valores de Y ingresados
    * en los campos de texto
    */

    /**Declaración del arreglo que guardará todos los valores de X ingresados
    * en los campos de texto
    */
    double[]valorDeX;
    double[]valorDeX2;
    
    /**Declaración del arreglo que guardará todos los valores de X2 ingresados
     * en los campos de texto
    */
    double[]valorDeY;

    //Declaración del modelo de la tabla 1
    DefaultTableModel modelo = new DefaultTableModel();
    
    //Declaración del modelo de la tabla 2
    DefaultTableModel modelo2 = new DefaultTableModel();
    public MetodoRegresionMultiple() {
        
        initComponents();
        
        //Metodo para centrar pantalla
        this.setLocationRelativeTo(null);
        
         //Columnas agregadas a la tabla 1
        modelo.addColumn("n");
        modelo.addColumn("Sumatoria x");
        modelo.addColumn("Sumatoria x2");
        modelo.addColumn("Sumatoria Y");
        modelo.addColumn("Sumatoria x1^2");
        modelo.addColumn("Sumatoria x1*x2");
        modelo.addColumn("Sumatoria x1*y");
        modelo.addColumn("Sumatoria x2*y");
        
        //Columnas agregadas a la tabla 2
        
        modelo2.addColumn("Y");
        modelo2.addColumn("Aprox.");
        
        //Se inicia n con un valor de 2 puntos predeterminadamente
        n = 2;
        
        //Establecimiento de modelo 1 a la tabla 1 y establecimiento del grosor de la fila
        tablaValores.setModel(modelo);
        tablaValores.setRowHeight(27);
        
        //Establecimiento de modelo 2 a la tabla 2 y establecimiento del grosor de la fila 
        tablaValores2.setModel(modelo2);
        tablaValores2.setRowHeight(50);
        
        //Aqui se agregan los JTextField a la matriz de JTextField
        campo[0][0]=campo00;
        campo[1][0]=campo10;
        campo[2][0]=campo20;
        campo[3][0]=campo30;
        campo[4][0]=campo40;
        campo[5][0]=campo50;
        campo[6][0]=campo60;
        campo[7][0]=campo70;
        campo[8][0]=campo80;
        campo[9][0]=campo90;
        
        campo[0][1]=campo01;
        campo[1][1]=campo11;
        campo[2][1]=campo21;
        campo[3][1]=campo31;
        campo[4][1]=campo41;
        campo[5][1]=campo51;
        campo[6][1]=campo61;
        campo[7][1]=campo71;
        campo[8][1]=campo81;
        campo[9][1]=campo91;
        
        campo[0][2]=campo02;
        campo[1][2]=campo12;
        campo[2][2]=campo22;
        campo[3][2]=campo32;
        campo[4][2]=campo42;
        campo[5][2]=campo52;
        campo[6][2]=campo62;
        campo[7][2]=campo72;
        campo[8][2]=campo82;
        campo[9][2]=campo92;
     
        generarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCampos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboCantidad = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo00 = new javax.swing.JTextField();
        campo01 = new javax.swing.JTextField();
        campo10 = new javax.swing.JTextField();
        campo11 = new javax.swing.JTextField();
        campo20 = new javax.swing.JTextField();
        campo21 = new javax.swing.JTextField();
        campo30 = new javax.swing.JTextField();
        campo31 = new javax.swing.JTextField();
        campo40 = new javax.swing.JTextField();
        campo41 = new javax.swing.JTextField();
        campo50 = new javax.swing.JTextField();
        campo60 = new javax.swing.JTextField();
        campo61 = new javax.swing.JTextField();
        campo70 = new javax.swing.JTextField();
        campo71 = new javax.swing.JTextField();
        campo80 = new javax.swing.JTextField();
        campo81 = new javax.swing.JTextField();
        campo90 = new javax.swing.JTextField();
        campo91 = new javax.swing.JTextField();
        campo51 = new javax.swing.JTextField();
        txtEcuacionDeLaRecta = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        campo02 = new javax.swing.JTextField();
        campo12 = new javax.swing.JTextField();
        campo22 = new javax.swing.JTextField();
        campo32 = new javax.swing.JTextField();
        campo42 = new javax.swing.JTextField();
        campo52 = new javax.swing.JTextField();
        campo62 = new javax.swing.JTextField();
        campo72 = new javax.swing.JTextField();
        campo82 = new javax.swing.JTextField();
        campo92 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaValores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaValores2 = new javax.swing.JTable();
        panelGrafica = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método Regresión Lineal Multiple");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        panelCampos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad de Puntos");

        comboCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("X1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Y");

        campo00.setText("1");
        campo00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo00ActionPerformed(evt);
            }
        });

        campo10.setText("2");

        campo20.setText("3");

        campo30.setText("4");

        campo40.setText("5");

        campo50.setText("6");

        campo60.setText("7");

        campo70.setText("8");

        campo80.setText("9");

        campo90.setText("10");

        txtEcuacionDeLaRecta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtEcuacionDeLaRecta.setText("Y = a2x2+a1x1+a0");

        btnResolver.setText("Aceptar");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("X2");

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEcuacionDeLaRecta, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(btnResolver, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addGroup(panelCamposLayout.createSequentialGroup()
                                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboCantidad, 0, 63, Short.MAX_VALUE)
                                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campo90, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campo80, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campo60, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campo50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(campo70, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(29, 29, 29)
                                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campo82)
                                    .addComponent(campo72)
                                    .addComponent(campo62)
                                    .addComponent(campo52)
                                    .addComponent(campo42)
                                    .addComponent(campo32)
                                    .addComponent(campo22)
                                    .addComponent(campo12)
                                    .addComponent(campo02)
                                    .addComponent(btnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo92))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))))
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(campo81)
                        .addComponent(campo71)
                        .addComponent(campo41)
                        .addComponent(campo31)
                        .addComponent(campo21)
                        .addComponent(campo11)
                        .addComponent(campo01, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addComponent(campo61)
                        .addComponent(campo51)
                        .addComponent(campo91)))
                .addGap(14, 14, 14))
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(campo61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(campo60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCamposLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAplicar)
                                .addComponent(btnNuevo)
                                .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(campo62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campo92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(txtEcuacionDeLaRecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResolver)
                .addGap(18, 18, 18))
        );

        tablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaValores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Aplicando la formula");

        tablaValores2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaValores2);

        panelGrafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnMenu.setBackground(new java.awt.Color(102, 102, 255));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMenu.setText("Menu Principal");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setOpaque(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed

        //Invocación del metodo Generar Campos
        generarCampos();
    }//GEN-LAST:event_btnAplicarActionPerformed

       /**
     * Este metodo pondrá visible todos los campos necesarios para poder 
     * ingresar valores de acuerdo al valor de la variable global n que se
     * obtiene al recibir su valor del comboBox que expresa el número de puntos
     */
    private void generarCampos(){
    
        //Se iguala n al valor obtenido de comboBox
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se ponen ocultos todos los campos de texto momentaneamente
        for (int i = 0; i < 10; i++) {
            
            for (int j = 0; j < 3; j++) {
             
                campo[i][j].setEnabled(false);
            }
        }
        
        /**
         * Se ponen visibles todos los campos necesarios para poder ingresar los
         * valores de n número de puntos
         */
        for (int i = 0; i < n; i++) {
            
            for (int j = 0; j < 3; j++) {
                
                campo[i][j].setEnabled(true);
            }
        }
    }
    private void campo00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo00ActionPerformed

       /**
     * Este metodo tiene la funcionalidad de obtener todos los valores 
     *  en los campos de texto y así crear dos vectores con los valores de X
     * y Y
     */
    private void generarArreglosDeVariables(){
        
        //Se obtiene la longitud de los vectores
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se iguala la longitud de los vectores a n
        valorDeX = new double[n];
        valorDeY = new double[n];
        valorDeX2 = new double[n];

        //Se inicia un bucle for en el que se añadirán los valores de x al vector
        //de 1 por 1
        
        for (int i = 0; i < n; i++) {
            
            valorDeX[i] = Double.parseDouble(campo[i][0].getText());
        }
        //Se inicia un bucle for en el que se añadirán los valores de x al vector
        //de 1 por 1
        for (int i = 0; i <n; i++) {
            
            valorDeY[i] = Double.parseDouble(campo[i][1].getText());

        }
        for (int i = 0; i <n; i++) {
            
            valorDeX2[i] = Double.parseDouble(campo[i][2].getText());
        }
        
        
    }
    
    /**
     * Este metodo tiene la funcionalidad de sumar todos los elementos de un
     * arreglo de tipo doble
     * @param arreglo de tipo double
     * @return sumatoriaArreglo
     */
    private double sumatoriaArreglo(double[]arreglo){
    
        //Se obtiene la longitd del arreglo a analizar
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se inicia la sumatoria en 0
        double sumatoriaArreglo = 0;
        
        //Se va sumando 1 a 1 los elementos del arreglo en un bucle for
        for (int i = 0; i < n; i++) {
            
            sumatoriaArreglo += arreglo[i];
        }
        
        return sumatoriaArreglo;
    }
    
     /**
     * Este metodo tiene la funcionalidad de crear un vector con la información
     * obtenida de x previamente pero al cuadrado
     */
    double[]xAlCuadrado;
    private void generarArregloXAlCuadrado(){
    
        //Se obtiene la longitud del vector
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se iguala la longitud del vector a n
        xAlCuadrado = new double[n];
        
        //Se van ingresando los valores al vector de x al cuadrado de 1 por 1
       //en un bucle for
        for (int i = 0; i < n; i++) {
            
            xAlCuadrado[i] = Math.pow(valorDeX[i], 2);
            
        }
    }
    /**
     * Este metodo tiene la funcionalidad de crear un vector con la información
     * obtenida de x2 previamente pero al cuadrado
     */
    double[]x2AlCuadrado;
    private void generarArregloX2AlCuadrado(){
    
        //Se obtiene la longitud del vector
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se iguala la longitud del vector a n
        x2AlCuadrado = new double[n];
        
        //Se van ingresando los valores al vector de x2 al cuadrado de 1 por 1
       //en un bucle for
        for (int i = 0; i < n; i++) {
            
            x2AlCuadrado[i] = Math.pow(valorDeX2[i], 2);
            
        }
    }
    double[]productox1Porx2;
    double[]productox1PorY;
    double[]productox2PorY;
    private void generarArreglosProductos() {
        
        //Se obtiene la longitud del vector
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
        
        //Se iguala la longitud del vector a n
        productox1Porx2 = new double[n];
        productox1PorY = new double[n];
        productox2PorY = new double[n];
        
        //Se van ingresando los valores al vector de x multiplicado por
        //x2 de 1 por 1 en un bucle for
        for (int i = 0; i < n; i++) {
         
            productox1Porx2[i] = valorDeX[i]*valorDeX2[i];
            
        }
        for (int i = 0; i < n; i++) {
         
            productox1PorY[i] = valorDeX[i]*valorDeY[i];
            
        }
        for (int i = 0; i < n; i++) {
         
            productox2PorY[i] = valorDeX2[i]*valorDeY[i];
            
        }
        
    }
    
    double[][]matriz;
    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        //Bloque try en caso de que suceda alguna excepción
        try {
            generarArreglosDeVariables();
            generarArregloXAlCuadrado();
            generarArregloX2AlCuadrado();
            generarArreglosProductos();

            double sumatoriax1 = sumatoriaArreglo(valorDeX);
            double sumatoriax2 = sumatoriaArreglo(valorDeX2);
            double sumatoriay = sumatoriaArreglo(valorDeY);
            double sumatoriaXAlCuadrado = sumatoriaArreglo(xAlCuadrado);
            double sumatoriaX2AlCuadrado = sumatoriaArreglo(x2AlCuadrado);
            double sumatoriax1Porx2 = sumatoriaArreglo(productox1Porx2);
            double sumatoriax1PorY = sumatoriaArreglo(productox1PorY);
            double sumatoriax2PorY = sumatoriaArreglo(productox2PorY);

            //Valores de la tabla 1 para evitar campos duplicados
            limpiarTabla(modelo);

            //Se ingresan los valores sumatoriaX, sumatoriaY, sumatoriaXAlCuadrado,
            //sumatoriaProductoXPorY, promedioX, promedioY y n
            //redondeados a 2 cifras en la tabla 1
            String[]valoresTabla = new String[8];
            valoresTabla[0] = String.valueOf(n);
            valoresTabla[1] = String.valueOf(String.format("%.2f", sumatoriax1));
            valoresTabla[2] = String.valueOf(String.format("%.2f", sumatoriax2));
            valoresTabla[3] = String.valueOf(String.format("%.2f", sumatoriay));
            valoresTabla[4] = String.valueOf(String.format("%.2f", sumatoriaXAlCuadrado));
            valoresTabla[5] = String.valueOf(String.format("%.2f", sumatoriax1Porx2));
            valoresTabla[6] = String.valueOf(String.format("%.2f", sumatoriax1PorY));
            valoresTabla[7] = String.valueOf(String.format("%.2f", sumatoriax2PorY));

            modelo.addRow(valoresTabla);

            matriz = generarMatriz(sumatoriax1, sumatoriax2, sumatoriay, sumatoriaXAlCuadrado,
                sumatoriax1Porx2, sumatoriax1PorY, sumatoriaX2AlCuadrado, sumatoriax2PorY);

            //Aplicación del metodo de Gauss Jordan
            double divisor;

            int contador=0;

            do{

                divisor = matriz[contador][contador];

                //Divide la fila a analizar entre su diagonal para igualar el primer
                //valor a 1
                for (int i = 0; i < 4; i++) {

                    matriz[contador][i] =  matriz[contador][i]/divisor;
                }

                //Convertir a 0 las las columnas

                for (int i = 0; i < 3; i++) {

                    double producto = matriz[contador][contador]*matriz[i][contador];

                    for (int j = 0; j < 4; j++) {

                        if (i!=contador) {

                            matriz[i][j] -= matriz[contador][j]*producto;
                        }
                    }
                }

                /**
                * Se muestra en el programa el valor de Y en función de la ecuación
                * generada por el metodo de regresión Lineal Multiple
                */
                txtEcuacionDeLaRecta.setText("Y = "+String.format("%.2f", matriz[2][3])
                    +"x2+"+String.format("%.2f", matriz[1][3])+"x1+"+String.format("%.2f", matriz[0][3]));

                contador++;
                //Se limpian los valores de la tabla 2
                limpiarTabla(modelo2);

                /**
                * Se ingresan en la tabla 2, los valores de Y ingresados
                * previamente y las aproximaciones en función de la ecuación
                * generada por el metodo de regresión Lineal Multiple
                */
                String[]valoresTabla2 = new String[2];

                for (int i = 0; i < n; i++) {

                    valoresTabla2[0]=String.valueOf(String.format("%.2f", valorDeY[i]));

                    valoresTabla2[1]= String.valueOf(String.format("%.2f",(matriz[2][3]*valorDeX2[i])+
                        (matriz[1][3]*valorDeX[i])+
                        (matriz[0][3])));
                modelo2.addRow(valoresTabla2);
            }

        }while(contador<n);

        }catch(Exception e){

            generarGrafica();
        }
        generarGrafica();
    }//GEN-LAST:event_btnResolverActionPerformed

       /**
     * Este metodo generá un gráfica de las aproximaciones de Y usando la 
     * Libreria JFreeChart al dar click en el botón Aceptar
     */
    private void generarGrafica(){
    
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //Se van agregandos los elementos de Y en funcion de la función obtenida
        //por el metodo de regresión lineal multiple
        for (int i = 0; i < n; i++) {

            //Puntos dados previamente
            dataset.addValue(((matriz[2][3]*i)+
                (matriz[1][3]*i)+
                (matriz[0][3])), "Aproximación generada por Regresión Lineal Multiple", "" + i);

        }

        JFreeChart chart = ChartFactory.createLineChart(
                "Grafica Regresión Lineal Multiple",
                "X1",
                "Y",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                false,
                false
        );

        //Mostramos la grafica en pantalla
        ChartPanel panel = new ChartPanel(chart);        
        panelGrafica.setLayout(new java.awt.BorderLayout());
        panelGrafica.add(panel);   
        panelGrafica.validate();
    }
    
    /**
     * Este metodo limpia las tablas de un modelo dado
     * @param modeloTabla a limpiar
     */
    private void limpiarTabla(DefaultTableModel modeloTabla){
    
        int filas = modeloTabla.getRowCount();
            
            for (int i = 0;filas>i; i++) {
                
                modeloTabla.removeRow(0);
            }
    }
    
    /**
     * Este metodo se encarga de generar la matriz en la que se aplicará el
     * método de Gauss Jordan para obtener los valores de a2, a1 y a
     * @param sumatoriax1
     * @param sumatoriax2
     * @param sumatoriaY
     * @param sumatoriax1AlCuadrado
     * @param sumatoriax1PorX2
     * @param sumatoriax1PorY
     * @param sumatoriax2AlCuadrado
     * @param sumatoriax2PorY
     * @return 
     */
private double[][]generarMatriz(double sumatoriax1, double sumatoriax2, double sumatoriaY,
        double sumatoriax1AlCuadrado, double sumatoriax1PorX2, double sumatoriax1PorY,
        double sumatoriax2AlCuadrado, double sumatoriax2PorY){

    double[][]sistema=new double [3][4];
    
    n = Integer.parseInt(comboCantidad.getSelectedItem().toString());
    
    sistema[0][0] = n;
    sistema[0][1] = sumatoriax1;
    sistema[0][2] = sumatoriax2;
    sistema[0][3] = sumatoriaY;
    
    sistema[1][0] = sumatoriax1;
    sistema[1][1] = sumatoriax1AlCuadrado;
    sistema[1][2] = sumatoriax1PorX2;
    sistema[1][3] = sumatoriax1PorY;
    
    sistema[2][0] = sumatoriax2;
    sistema[2][1] = sumatoriax1PorX2;
    sistema[2][2] = sumatoriax2AlCuadrado;
    sistema[2][3] = sumatoriax2PorY;
    
    return sistema;
}

/**
 * Este metodo es utilizado para vaciar la gráfica generada anteriormente
 */
private void generarGraficaVacia(){
    
        XYSeries series = new XYSeries("");
        

        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);

        JFreeChart chart = ChartFactory.createXYLineChart(
                "Gráfica",
                "X",
                "Y",
                dataset,
                PlotOrientation.VERTICAL,
                false,
                false,
                false
        );

        // Mostramos la grafica dentro del jPanel1
        ChartPanel panel = new ChartPanel(chart);        
        panelGrafica.setLayout(new java.awt.BorderLayout());
        panelGrafica.add(panel);   
        panelGrafica.validate();
    }

     /**
     * Este metodo vaciio sirve para borrar todos los datos de las tablas, generar una
     * gráfica vacia, y establecer el número de puntos en 2 con campos de texto
     * generados para pedir 2 puntos. Se utilizará despues de realizar el metodo
     * de regresión lineal multiple y querer calcular otro
     * @param evt al hacer click en el boton Nuevo
     */
                                       

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        //Se invoca el metodo para limpiar ambas tablas
        limpiarTabla(modelo);
        limpiarTabla(modelo2);

        /**
        * Este bucle for servirá para borrar todo lo escrito en los campos
        * y para ocultar todos los campos momentaneamente
        */
        for (int i = 0; i < 10; i++) {

            for (int j = 0; j < 3; j++) {
                campo[i][j].setEnabled(false);
                campo[i][j].setText(null);
            }
        }

        /**
        * Luego de borrar y ocultar todos los campos, se pondrán visibles los
        * primeros 6, para establecer los puntos disponibles en 2
        */
        for (int i = 0; i < 2; i++) {

            for (int j = 0; j < 3; j++) {

                campo[i][j].setEnabled(true);
            }
        }

        /**
        * Se seleccionará el indice 0 del comboBox, el cual tendrá un valor de
        * 2, esto servirá para poder darle este valor a n
        */
        this.comboCantidad.setSelectedIndex(0);

        /**
        * Se establecerá el valor de n de acuerdo al valor obtenido del
        * comboBox, el cual fue establecido previamente
        */
        n = Integer.parseInt(comboCantidad.getSelectedItem().toString());

        //Se genera una gráfica XY vacia
        generarGraficaVacia();

        //Se inserta 1 en el primer valor de X
        campo00.setText("1");
        //Se inserta 2 en el segundo valor de X
        campo10.setText("2");

        txtEcuacionDeLaRecta.setText("Y = ax+b");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnResolver;
    private javax.swing.JTextField campo00;
    private javax.swing.JTextField campo01;
    private javax.swing.JTextField campo02;
    private javax.swing.JTextField campo10;
    private javax.swing.JTextField campo11;
    private javax.swing.JTextField campo12;
    private javax.swing.JTextField campo20;
    private javax.swing.JTextField campo21;
    private javax.swing.JTextField campo22;
    private javax.swing.JTextField campo30;
    private javax.swing.JTextField campo31;
    private javax.swing.JTextField campo32;
    private javax.swing.JTextField campo40;
    private javax.swing.JTextField campo41;
    private javax.swing.JTextField campo42;
    private javax.swing.JTextField campo50;
    private javax.swing.JTextField campo51;
    private javax.swing.JTextField campo52;
    private javax.swing.JTextField campo60;
    private javax.swing.JTextField campo61;
    private javax.swing.JTextField campo62;
    private javax.swing.JTextField campo70;
    private javax.swing.JTextField campo71;
    private javax.swing.JTextField campo72;
    private javax.swing.JTextField campo80;
    private javax.swing.JTextField campo81;
    private javax.swing.JTextField campo82;
    private javax.swing.JTextField campo90;
    private javax.swing.JTextField campo91;
    private javax.swing.JTextField campo92;
    private javax.swing.JComboBox<String> comboCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JTable tablaValores;
    private javax.swing.JTable tablaValores2;
    private javax.swing.JLabel txtEcuacionDeLaRecta;
    // End of variables declaration//GEN-END:variables
}
