/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pmn.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author enriq_000
 */
public class MetodoMatrizInversa extends javax.swing.JFrame {

    /**
     * Creates new form MetodoMatrizInversa
     */
    
    JTextField[][]campos = new JTextField[5][6];
    JLabel[]variables = new JLabel[6];
    
    JTextField[][]camposInversa = new JTextField[3][6];
    JLabel[]variablesInversa = new JLabel[6];
    
    int n;
    int m;
    private double tolerancia = 1; 
    
    public MetodoMatrizInversa() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        camposInversa[0][0] = inversa00;
        camposInversa[0][1] = inversa01;
        camposInversa[0][2] = inversa02;
        camposInversa[0][3] = inversa03;
        camposInversa[0][4] = inversa04;
        camposInversa[0][5] = inversa05;
        
        camposInversa[1][0] = inversa10;
        camposInversa[1][1] = inversa11;
        camposInversa[1][2] = inversa12;
        camposInversa[1][3] = inversa13;
        camposInversa[1][4] = inversa14;
        camposInversa[1][5] = inversa15;
        
        camposInversa[2][0] = inversa20;
        camposInversa[2][1] = inversa21;
        camposInversa[2][2] = inversa22;
        camposInversa[2][3] = inversa23;
        camposInversa[2][4] = inversa24;
        camposInversa[2][5] = inversa25;
        
        variablesInversa[0] = inversa0;
        variablesInversa[1] = inversa1;
        variablesInversa[2] = inversa2;
        variablesInversa[3] = inversa3;
        variablesInversa[4] = inversa4;
        variablesInversa[5] = inversa5;
        
        n=2;
        m=2;
        
        generarCamposInversa();
        generarVariablesInversa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboLongitud1 = new javax.swing.JComboBox<>();
        btnAplicar1 = new javax.swing.JButton();
        inversa0 = new javax.swing.JLabel();
        inversa1 = new javax.swing.JLabel();
        inversa2 = new javax.swing.JLabel();
        inversa3 = new javax.swing.JLabel();
        inversa4 = new javax.swing.JLabel();
        inversa5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inversa00 = new javax.swing.JTextField();
        inversa01 = new javax.swing.JTextField();
        inversa02 = new javax.swing.JTextField();
        inversa03 = new javax.swing.JTextField();
        inversa04 = new javax.swing.JTextField();
        inversa05 = new javax.swing.JTextField();
        inversa10 = new javax.swing.JTextField();
        inversa11 = new javax.swing.JTextField();
        inversa12 = new javax.swing.JTextField();
        inversa13 = new javax.swing.JTextField();
        inversa15 = new javax.swing.JTextField();
        inversa14 = new javax.swing.JTextField();
        inversa20 = new javax.swing.JTextField();
        inversa21 = new javax.swing.JTextField();
        inversa22 = new javax.swing.JTextField();
        inversa23 = new javax.swing.JTextField();
        inversa25 = new javax.swing.JTextField();
        inversa24 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo Matriz Inversa");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matriz Inversa");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número de variables");

        comboLongitud1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3" }));

        btnAplicar1.setText("Aplicar");
        btnAplicar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicar1ActionPerformed(evt);
            }
        });

        inversa0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inversa0.setText("X");

        inversa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inversa1.setText("Y");

        inversa2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inversa2.setText("X^-1");

        inversa3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inversa3.setText("Y^-1");

        inversa4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        inversa5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inversa00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversa00ActionPerformed(evt);
            }
        });

        inversa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversa10ActionPerformed(evt);
            }
        });

        inversa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversa20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inversa00, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa01, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa02, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa03, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa04, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa05, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inversa10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inversa20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inversa24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inversa25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inversa00, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inversa01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inversa10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inversa11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inversa20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inversa25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inversa21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnCalcular.setBackground(new java.awt.Color(102, 102, 255));
        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(102, 102, 255));
        btnMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMenu.setText("Menú Principal");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setOpaque(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboLongitud1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAplicar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(inversa0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(inversa1)
                                .addGap(40, 40, 40)
                                .addComponent(inversa2)
                                .addGap(33, 33, 33)
                                .addComponent(inversa3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(inversa4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inversa5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnAplicar1)
                    .addComponent(comboLongitud1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inversa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inversa1)
                        .addComponent(inversa2)
                        .addComponent(inversa3)
                        .addComponent(inversa0))
                    .addComponent(inversa4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    Metodo encargado de mostrar las variables en pantalla dependiendo de la 
    cantidad
    */
    private void generarVariablesInversa(){
    
        switch (m){
        
            case 2:
                variablesInversa[0].setText("X");
                variablesInversa[1].setText("Y");
                variablesInversa[2].setText("X^-1");
                variablesInversa[3].setText("Y^-1");
                variablesInversa[4].setText(null);
                variablesInversa[5].setText(null);
                break;
                
            case 3:
                variablesInversa[0].setText("X");
                variablesInversa[1].setText("Y");
                variablesInversa[2].setText("Z");
                variablesInversa[3].setText("X^-1");
                variablesInversa[4].setText("Y^-1");
                variablesInversa[5].setText("Z^-1");
                break;
        
        }
    }
    
    /**
     * Metodo encargado de generar los campos necesarios para poder aplicar el
     * metodo de matriz inversa de acuerdo al número de variables
     */
    private void generarCamposInversa(){
    
        switch(m){
        
        case 2:
            for (int i = 0; i < 3; i++) {
            
            for (int j = 0; j < 6; j++) {
                
                camposInversa[i][j].setEnabled(false);
                camposInversa[i][j].setText(null);
            }
        }
        
            for (int i = 0; i < m; i++) {
            
                for (int j = 0; j < m*2; j++) {
                
                    camposInversa[i][j].setEnabled(true);
                    inversa02.setText("1");
                    inversa03.setText("0");
                    inversa12.setText("0");
                    inversa13.setText("1");
                    
                    inversa02.setEnabled(false);
                    inversa03.setEnabled(false);
                    inversa12.setEnabled(false);
                    inversa13.setEnabled(false);
                    
            }
        }    
                break;
                
        case 3:
            for (int i = 0; i < 3; i++) {
            
            for (int j = 0; j < 6; j++) {
                
                camposInversa[i][j].setEnabled(false);
                camposInversa[i][j].setText(null);
            }
        }
        
            for (int i = 0; i < m; i++) {
            
                for (int j = 0; j < m*2; j++) {
                
                    camposInversa[i][j].setEnabled(true);
                    inversa03.setText("1");
                    inversa04.setText("0");
                    inversa05.setText("0");
                    inversa13.setText("0");
                    inversa14.setText("1");
                    inversa15.setText("0");
                    inversa23.setText("0");
                    inversa24.setText("0");
                    inversa25.setText("1");
                    
                    inversa03.setEnabled(false);
                    inversa04.setEnabled(false);
                    inversa05.setEnabled(false);
                    inversa13.setEnabled(false);
                    inversa14.setEnabled(false);
                    inversa15.setEnabled(false);
                    inversa23.setEnabled(false);
                    inversa24.setEnabled(false);
                    inversa25.setEnabled(false);
                    
            }
        }    
                break;
        }   
    }

    /**
     * Evento encargado de generar los campos necesarios para poder trabajar 
     * con la matriz inversa
     * @param evt 
     */
    private void btnAplicar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicar1ActionPerformed

        m = Integer.parseInt(String.valueOf(comboLongitud1.getSelectedItem()));

        generarVariablesInversa();

        generarCamposInversa();
    }//GEN-LAST:event_btnAplicar1ActionPerformed

    private void inversa00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversa00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversa00ActionPerformed

    private void inversa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversa10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversa10ActionPerformed

    private void inversa20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversa20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversa20ActionPerformed

    double [][]sistemaInversa = new double[m][m*2];

    /**
     * Metodo encargado de generar la matriz inversa
     */
    private void generarMatrizInversa(){
        
        sistemaInversa = new double[m][m*2];
        
        for (int i = 0; i < m; i++) {
            
            for (int j = 0; j < m*2; j++) {
                
                sistemaInversa[i][j] = Double.parseDouble(camposInversa[i][j].getText());
            }
        }
    }
    
    String area="";
    
    /**
     * Evento encargado de generar el Método de Matriz Inversa
     * @param evt 
     */
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        try{
        area = "";
        generarMatrizInversa();
        
        double divisor;
  
        int contador=0;
        
        do{
            
            divisor=sistemaInversa[contador][contador];
            
        //Divide la fila a analizar entre su diagonal para igualar el primer
        //valor a 1
        for (int i = 0; i < m*2; i++) {
            
            sistemaInversa[contador][i] =  sistemaInversa[contador][i]/divisor;
        }
        
        //Convertir a 0 las las columnas
        
            for (int i = 0; i < m; i++) {
                
                double producto = sistemaInversa[contador][contador]*sistemaInversa[i][contador];
                        
                for (int j = 0; j < m*2; j++) {
                    
                    if (i!=contador) {
                        
                        sistemaInversa[i][j] -= sistemaInversa[contador][j]*producto;
                    }
                }
            }
            
              //Mostrar matrices paso por paso en consola  
            for (int x=0; x < sistemaInversa.length; x++) {
                
                area+="|";
                txtArea.setText(area);
                
            for (int y=0; y < sistemaInversa[x].length; y++) {
                
                area+=String.format("%.2f", sistemaInversa[x][y]);
                txtArea.setText(area);
                
            if (y!=sistemaInversa[x].length-1) 
                
                area+="\t";
                txtArea.setText(area);
            }
            area+="|"+"\n";
            txtArea.setText(area);
            }

        contador++;
        area+="________________________________"+"\n";
        txtArea.setText(area);
        
        }while(contador<m);
        
        area+="________________________________"+"\n";
        txtArea.setText(area);
        
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Asegurese de ingresar valores "
                    + "en todos los campos con el formato correcto");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar1;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> comboLongitud1;
    private javax.swing.JLabel inversa0;
    private javax.swing.JTextField inversa00;
    private javax.swing.JTextField inversa01;
    private javax.swing.JTextField inversa02;
    private javax.swing.JTextField inversa03;
    private javax.swing.JTextField inversa04;
    private javax.swing.JTextField inversa05;
    private javax.swing.JLabel inversa1;
    private javax.swing.JTextField inversa10;
    private javax.swing.JTextField inversa11;
    private javax.swing.JTextField inversa12;
    private javax.swing.JTextField inversa13;
    private javax.swing.JTextField inversa14;
    private javax.swing.JTextField inversa15;
    private javax.swing.JLabel inversa2;
    private javax.swing.JTextField inversa20;
    private javax.swing.JTextField inversa21;
    private javax.swing.JTextField inversa22;
    private javax.swing.JTextField inversa23;
    private javax.swing.JTextField inversa24;
    private javax.swing.JTextField inversa25;
    private javax.swing.JLabel inversa3;
    private javax.swing.JLabel inversa4;
    private javax.swing.JLabel inversa5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
